name: 'GitHub Actions Send Daily to Telegram or Feishu'

on:
  push:
    branches: [main]
  schedule:
    - cron: '0/5 0,4,5,6,7,8,10,12,14 * * *'


jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: 'Install node'
        uses: actions/setup-node@v1

      - name: 'Install NPM dependencies'
        run: npm install

      - name: 'Run node'
        run: node index.js

        env:
          SEND_TYPE: ${{ secrets.SEND_TYPE }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          
